### ISSUE TITLE
advanced buttons issue

### ISSUE THREAD

**Issue by C4Wiz** [gfjardim/unRAID-plugins#12]
with the latest version installed on 6.3 RC6, dockers do not stop and start properly, says container name not found skipping...it looks like its not seeing the - in the name.

IE: MakeMKV-RDP, it says MakeMKV not found skipping.

if i uninstall the plugin, the docker starts and stops fine

UPDATE: the start ALL and stop ALL buttons work fine, but trying to start them seperately does not work

**Comment by gfjardim** [comment]
Fixed in version 2016.12.21a.

Thanks for reporting!
