### ISSUE TITLE
rc.diskinfo being triggered during disk rebuild

### ISSUE THREAD

**Issue by veL556** [gfjardim/unRAID-plugins#16]
When replacing a disk and starting array & rebuild, rc.diskinfo is being triggered multiple times.

ug  9 00:26:33 Tower emhttpd: writing GPT on disk (sdr), with partition 1 offset 64, erased: 0
Aug  9 00:26:33 Tower emhttpd: shcmd (877): sgdisk -Z /dev/sdr
Aug  9 00:26:33 Tower kernel: sdr: sdr1
Aug  9 00:26:33 Tower rc.diskinfo[8879]: SIGHUP received, forcing refresh of disks info.
Aug  9 00:26:34 Tower rc.diskinfo[8879]: SIGHUP received, forcing refresh of disks info.
Aug  9 00:26:34 Tower kernel: sdr: sdr1
Aug  9 00:26:34 Tower root: 
Aug  9 00:26:34 Tower root: ***************************************************************
Aug  9 00:26:34 Tower root: Found invalid GPT and valid MBR; converting MBR to GPT format
Aug  9 00:26:34 Tower root: in memory. 
Aug  9 00:26:34 Tower root: ***************************************************************
Aug  9 00:26:34 Tower root: 
Aug  9 00:26:34 Tower root: GPT data structures destroyed! You may now partition the disk using fdisk or
Aug  9 00:26:34 Tower root: other utilities.
Aug  9 00:26:34 Tower emhttpd: shcmd (878): sgdisk -o -a 64 -n 1:64:0 /dev/sdr
Aug  9 00:26:35 Tower root: Creating new GPT entries.
Aug  9 00:26:35 Tower root: The operation has completed successfully.
Aug  9 00:26:35 Tower emhttpd: shcmd (879): udevadm settle
Aug  9 00:26:35 Tower kernel: sdr: sdr1
Aug  9 00:26:49 Tower rc.diskinfo[8879]: SIGHUP received, forcing refresh of disks info.
Aug  9 00:26:49 Tower rc.diskinfo[8879]: SIGHUP received, forcing refresh of disks info.
Aug  9 00:27:04 Tower rc.diskinfo[8879]: SIGHUP received, forcing refresh of disks info.
Aug  9 00:27:05 Tower rc.diskinfo[8879]: SIGHUP received, forcing refresh of disks info.
Aug  9 00:27:20 Tower rc.diskinfo[8879]: SIGHUP received, forcing refresh of disks info.
Aug  9 00:27:20 Tower rc.diskinfo[8879]: SIGHUP received, forcing refresh of disks info.
Aug  9 00:27:35 Tower rc.diskinfo[8879]: SIGHUP received, forcing refresh of disks info.
Aug  9 00:27:36 Tower rc.diskinfo[8879]: SIGHUP received, forcing refresh of disks info.
Aug  9 00:27:36 Tower kernel: mdcmd (49): start RECON_DISK

**Comment by gfjardim** [comment]
Yep, every time a change in disks or in partition tables are done, the diskinfo daemon is informed that it has to refresh all disk information
