### ISSUE TITLE
xhr spamming

### ISSUE THREAD

**Issue by veL556** [gfjardim/unRAID-plugins#17]
preclear spams xhr requests regardless of what UnRaid page the browser is currently viewing and when no preclears have been started or are running.

 If none have been started, I don't see what value there is to these xhr requests. Is there?

Is it possible to bound this such that xhr requests are only enabled if a preclear has been started?

**Comment by sasjafor** [comment]
I have also noticed those requests. They are actually more frequent than for SystemTemp. It seems a bit excessive. I get about 3 requests for preclear for every request for SystemTemp.
I think less frequent requests or no requests when no preclear is running / not on a preclear relevant unraid page would be good.

Maybe I'll also take a look at it myself and see what I can do.

**Comment by gfjardim** [comment]
@sasjafor, which version of Preclear script are you using? It should update the CSRF token if needed.

**Comment by sasjafor** [comment]
I am using:
Plugin version: 2018.10.07
Preclear script version: 1.15 (which i believe is the original version from JoeL, not the modified one with the notifications)

**Comment by gfjardim** [comment]
Could you please see if it's mitigated in the last version?

**Comment by sasjafor** [comment]
It does happen a lot less frequently when no preclear is running now. Can't test it with a preclear running as I don't have a disk to clear. I looked at the unraid settings page while there was no preclear icon in the bottom status bar.

**Comment by gfjardim** [comment]
It will close this for now, please open if you have any further problems.
